<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body class='container text-center mt-5 border'>
    <h2 class='alert alert-success mt-4'> <?php echo $t->_("Add Product"); ?></h2>
    <!-- ------------------------------ checking message from controller ----------------- ------------>

    <?php if (isset($msg)) {
        echo $msg;
    }; ?>
    <!-- -------------------------------------------Form starts ------------------------------------------------>

    <?php echo $this->tag->form(['', 'class' => 'my-5', 'method' => 'get']); ?>
    <p class="row">
        <label for="email" class='label col-2 mx-5'> <?php echo $t->_("Product Name"); ?></label>
        <?php echo $this->tag->textField(['product_name', 'class' => 'form-control col-6']) ?>
    </p>
    <p class="row">
        <label for="email" class='label col-2 mx-5'> <?php echo $t->_("Description"); ?></label>
        <?php echo $this->tag->textArea(['description', 'class' => 'form-control col-6']) ?>
    </p>
    <p class="row">
        <label for="email" class='label col-2 mx-5'> <?php echo $t->_("Tags"); ?></label>
        <?php echo $this->tag->textField(['tags', 'class' => 'form-control col-6']) ?>
    </p>
    <p class="row">
        <label for="email" class='label col-2 mx-5'> <?php echo $t->_("Price"); ?> </label>
        <?php echo $this->tag->textField(['price', 'class' => 'form-control col-6']) ?>
    </p>
    <p class="row">
        <label for="email" class='label col-2 mx-5'> <?php echo $t->_("Stock"); ?> </label>
        <?php echo $this->tag->textField(['stocks', 'class' => 'form-control col-6']) ?>
    </p>
    <p class="row">
        <label for="email" class='label col-2 mx-5'> Additional Fields</label>
        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-plus-circle" id="additionField" viewBox="0 0 16 16" onclick="additional_fields()">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
        </svg>
    <div id="container">
    </div>
    </p>
    <p class="row">
        <label for="email" class='label col-2 mx-5'> Variations</label>
        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-plus-circle" id="variatonField" viewBox="0 0 16 16" onclick="variation_fields()">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
        </svg>
    <div id="variation">
    </div>
    </p>

    <p>
        <?php echo $this->tag->submitButton([$t->_("Add Product"), 'class' => 'btn  btn-primary mx-5']); ?>
    </p>
    <?php echo $this->tag->endForm(); ?>
    <!-- -------------------------------------------Form starts ------------------------------------------------>

</body>
<script type='text/javascript'>
    let additional_fields_clicks = 0;
    let variation_fields_clicks = 0;

    function variation_fields() {
        variation_fields_clicks += 1;
        console.log(variation_fields_clicks);
        variation_fields_display();
        document.getElementById('variation').innerHTML = html;
    }


    function variation_fields_display() {
        html = '';
        for (var i = 1; i <= variation_fields_clicks; i++) {
            html += " <p class='row '> \
        <label class='label col-2 mx-5'> </label>\
        <input class='form-control col-2' name='variation_label" + i + "' placeholder='Name'>\
       &nbsp;&nbsp;&nbsp;&nbsp;\
        <input class='form-control col-2' name='variation_value" + i + "' placeholder='Value'> \
       &nbsp;&nbsp;&nbsp;&nbsp;\
        <input class='form-control col-2' type='text' name='variation_price" + i + "' placeholder='Price'>\
        <input type='button' onclick='variation_fields_remove()' id='remove" + i + "'value='Remove'>\
        <p>";
        }
        html += "<input class='form-control col-2' type='hidden' name='variation_count' value='" + variation_fields_clicks + "'>"
    }

    function variation_fields_remove(btn) {
        variation_fields_clicks -= 1;
        console.log(additional_fields_clicks)
        // btn.parentElement.remove(btn);

        variation_fields_display();
        document.getElementById('variation').innerHTML = html;
    }


    function additional_fields() {
        additional_fields_clicks += 1;
        console.log(additional_fields_clicks);
        additional_field_display();
        document.getElementById('container').innerHTML = html;

    }

    function additional_fields_remove(btn) {
        additional_fields_clicks -= 1;
        console.log(additional_fields_clicks)
        // btn.parentElement.remove(btn);

        additional_field_display();
        document.getElementById('container').innerHTML = html;
    }

    function additional_field_display() {
        html = '';
        for (var i = 1; i <= additional_fields_clicks; i++) {
            html += " <p class='row '> \
        <label class='label col-2 mx-5'> </label>\
        <input class='form-control col-2' name='label" + i + "' placeholder='label'>\
        <span class='col-1'> </span>\
        <input class='form-control col-2' name='value" + i + "' placeholder='value'> \
        <input class='form-control col-2' type='hidden' name='count' value='" + i + "'>&nbsp&nbsp\
        <input type='button' onclick='additional_fields_remove()' id='remove" + i + "'value='Remove'>\
        <p>";
        }

    }
</script>

</html>