<!---------------- Including Header ------------>
<?php echo $this->partial('index/header') ?>
<div class="row products mt-5 my-5">

    <!---------------------------------------------------- Buttons for Navigation----------------------------------------------->
    <div class="col-3 btn text-center p-3 border-danger  h4 mx-5 border mt-5">
        <?php echo $this->tag->linkTo('product/productList?locale=' . $_REQUEST['locale'], $t->_("Product List")) ?>
    </div>
    <div class="col-3 btn text-center p-3 border-danger  h4 mx-5 border mt-5">
        <?php echo $this->tag->linkTo('product/addProduct?locale=' . $_REQUEST['locale'], $t->_('Product Add')) ?>
    </div>
    <div class="col-3 btn text-center p-3 border-danger  h4 mx-5 border mt-5">
        <?php echo $this->tag->linkTo('order/orderList?locale=' . $_REQUEST['locale'], $t->_('Orders List')) ?>
    </div>

    <div class="col-3 btn text-center p-3 border-danger  h4 mx-5 border mt-5">
        <?php echo $this->tag->linkTo('order/addOrder?locale=' . $_REQUEST['locale'], $t->_('Order Add')) ?>

    </div>
    <div class="col-3 btn text-center p-3 border-danger  h4 mx-5 border mt-5">
        <?php echo $this->tag->linkTo('index/settings?locale=' . $_REQUEST['locale'], $t->_('Settings')) ?>

    </div>
    <div class="col-3 btn text-center p-3 border-danger  h4 mx-5 border mt-5">
        <?php echo $this->tag->linkTo('acl?locale=' . $_REQUEST['locale'], $t->_('Acl')) ?>

    </div>
    <div class="col-3 btn text-center p-3 border-danger  h4 mx-5 border mt-5">
        <?php echo $this->tag->linkTo('acl/data?locale=' . $_REQUEST['locale'], $t->_('Permissions')) ?>

    </div>
    <div class="col-3 btn text-center p-3 border-danger  h4 mx-5 border mt-5">
        <?php echo $this->tag->linkTo('user/addUser?locale=' . $_REQUEST['locale'], $t->_('Add User')) ?>

    </div>
    <div class="col-3 btn text-center p-3 border-danger  h4 mx-5 border mt-5">
        <?php echo $this->tag->linkTo('user/index?locale=' . $_REQUEST['locale'], $t->_('User Lists')) ?>
    </div>

</div>

<!---------------- Including Footer ------------>
<?php echo $this->partial('index/footer') ?>