<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body class='container text-center mt-5 border'>
    <!------------------------------------------ checking if role added or not ---------------------------------->

    <h2 class='alert alert-success mt-4'> <?php echo $t->_("Add Role"); ?></h2>
    <?php if (isset($msg)) {
        echo $msg;
    }; ?>

    <!-- -------------------------------------------Form for adding role --------------------------------------->

    <?php echo $this->tag->form(['', 'class' => 'my-5']); ?>
    <p class="row">
        <label for="email" class='label col-2 mx-5 h4 text-bold'><?php echo $t->_("Role"); ?></label>
        <?php echo $this->tag->textField([$t->_('roles'), 'class' => 'form-control col-6']) ?>
    </p>
    <p>
        <?php echo $this->tag->submitButton([$t->_("Add Role"), 'class' => 'btn  btn-primary mx-5']); ?>
    </p>
    <?php echo $this->tag->endForm(); ?>
    <!-- -----------------------------------------------------Form ends -------------------------------------------------->

</body>

</html>